      const monsterImg = {
        rathalos: "img/Rathalos.png",
        zinogre: "img/zinogre.png",
        aptonoth: "img/aptonoth.png",
        jagras: "img/jagras.png",
        mernos: "img/mernos.png",
        vespoid: "img/vespoid.png",
        mosswine: "img/mosswine.png",
        apceros: "img/apceros.png",
        kestodon: "img/kestodon.png",
        noios: "img/noios.png",
        gajau: "img/gajau.png",
        kelbi: "img/kelbi.png",
        raphinos: "img/raphinos.png",
        shamos: "img/shamos.png",
        girros: "img/girros.png",
        hornetaur: "img/hornetaur.png",
        gastodon: "img/gastodon.png",
        barnos: "img/barnos.png",
        "great jagras": "img/great jagras.png",
        "kulu-ya-ku": "img/kulu-ya-ku.png",
        "pukei-pukei": "img/pukei-pukei.png",
        barroth: "img/barroth.png",
        jyuratodus: "img/jyuratodus.png",
        "tobi-kadachi": "img/tobi-kadachi.png",
        anjanath: "img/anjanath.png",
        "azure rathalos": "img/azure rathalos.png",
        bazelgeuse: "img/bazelgeuse.png",
        behemoth: "img/behemoth.png",
        deviljho: "img/deviljho.png",
        diablos: "img/diablos.png",
        "black diablos": "img/black diablos.png",
        dodogama: "img/dodogama.png",
        "great girros": "img/great girros.png",
        kirin: "img/kirin.png",
        "kulve taroth": "img/kulve taroth.png",
        "kushala daora": "img/kushala daora.png",
        lavasioth: "img/lavasioth.png",
        legiana: "img/legiana.png",
        lunastra: "img/lunastra.png",
        nergigante: "img/nergigante.png",
        odogaron: "img/odogaron.png",
        paolumu: "img/paolumu.png",
        radobaan: "img/radobaan.png",
        rathian: "img/rathian.png",
        "pink rathian": "img/pink rathian.png",
        teostra: "img/teostra.png",
        "tzitzi-ya-ku": "img/tzitzi-ya-ku.png",
        uragaan: "img/uragaan.png",
        "vaal hazak": "img/vaal hazak.png",
        "xeno'jiiva": "img/xeno'jiiva.png",
        "zorah magdaros": "img/zorah magdaros.png",
        leshen: "img/leshen.png",
        "ancient leshen": "img/ancient leshen.png",
        "safi'jiiva": "img/safi'jiiva.png",
        "stygian zinogre": "img/stygian zinogre.png",
        rajang: "img/rajang.png",
        "viper tobi-kadachi": "img/viper tobi-kadachi.png",
        namielle: "img/namielle.png",
      };

      export function getMonsterIcon(name) {
        return monsterImg[name.toLowerCase()];
      }
